import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Life Journal Plugin · 记录即意义
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: false,  // ⚠️ 关闭 tree-shaking，确保 ReviewView 等类不被优化掉
  outfile: "main.js",
  minify: prod,
  charset: "utf8",    // 保留中文/emoji 原始 UTF-8 编码，避免 \uXXXX 转义导致渲染异常
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
