import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Life Journal Plugin 路 璁板綍鍗虫剰涔?
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: false,  // 鈿狅笍 鍏抽棴 tree-shaking锛岀‘淇?ReviewView 绛夌被涓嶈浼樺寲鎺?
  outfile: "main.js",
  minify: prod,
  charset: "utf8",    // 淇濈暀涓枃/emoji 鍘熷 UTF-8 缂栫爜锛岄伩鍏?\uXXXX 杞箟瀵艰嚧娓叉煋寮傚父
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
